#!/usr/bin/env node
const args = require('minimist')(process.argv);
const PORT = process.env.PORT || args.p || args.port || 3000;
const path = require('path');
const express = require("express");
const app = express();
const http = require('http').Server(app);
const io = require('socket.io')(http);
const morgan = require('morgan')
const Core = require('./src/core');

app.use(morgan('dev'));
app.use(express.static(path.join(__dirname, 'public')));

app.get('*', (req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));

const core = new Core(io);
core.initSystem().then(function() {
  http.listen(PORT);
  console.log('listening on '+PORT);
})

